Initial
marsiitr/3D-Mapping- pull request #1
Opened 2018-07-06 03:45 UTC by kalpgarg

2018-07-06 06:15 UTC, Shubhanshu07 commented
@kalpgarg It's looking nice.
Before merging it need a change.
1. Add names of team member and mentor name in Readme file in alphabetical order.
2.  Electronics part and arduino is not present in it.
3. What does this src folder signify?

2018-07-06 06:31 UTC, palnabarun commented
@Shubhanshu07 `src` is generally used to store source codes of a project. Ideally, every project should have used this folder to store the code.

2018-07-06 06:33 UTC, palnabarun requested changes

2018-07-06 06:33 UTC, palnabarun commented on readme.md
> +This whole work is being developed in ROS(Robot Operating System). It is being chosen due to its simple usage to implement various different components and pacjkages used for robot  building and to i
Please remove the <br/> tags. Paragraphs in markdown are denoted by a black line.

2018-07-06 06:33 UTC, palnabarun commented
@kalpgarg Please try to put some effort into the commit messages.

2018-07-08 05:18 UTC, agshubhs approved these changes

2018-07-08 05:19 UTC, Shubhanshu07 commented
It looks good to me.

2018-07-08 05:19 UTC, merged